version: '3.8'

networks:
  net:
    name: net

services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - .:/var/www/html
    networks:
      - net

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - net

  phpunit:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpunit
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: [ '/var/www/html/vendor/bin/phpunit' ]
    networks:
      - net